version: "3.9"

services:
  database:
    image: mariadb:11.4
    container_name: ptero_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /srv/pterodactyl/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: STRONG_ROOT_PASSWORD
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: STRONG_DB_PASSWORD

  redis:
    image: redis:7-alpine
    container_name: ptero_redis
    restart: unless-stopped

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: ptero_panel
    restart: unless-stopped

    depends_on:
      - database
      - redis

    ports:
      - "80:80"

    volumes:
      - /srv/pterodactyl/var:/app/var
      - /srv/pterodactyl/logs:/app/storage/logs
      - /srv/pterodactyl/nginx:/etc/nginx/http.d
      - /srv/pterodactyl/certs:/etc/letsencrypt

    environment:
      APP_URL: https://didactic-engine-x56xg9vrvrj4hpg5q-80.app.github.dev
      APP_TIMEZONE: Asia/Jakarta
      APP_SERVICE_AUTHOR: admin@example.com
      APP_ENV: production
      APP_DEBUG: "false"
      RECAPTCHA_ENABLED: "false"

      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: STRONG_DB_PASSWORD

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis

      REDIS_HOST: redis

networks:
  default:
    name: pterodactyl_network
